definitions:
  controllers.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  controllers.SuccessResponse:
    properties:
      message:
        type: string
      searchTerm:
        type: string
      suggestions:
        items:
          $ref: '#/definitions/models.City'
        type: array
    type: object
  models.City:
    properties:
      country:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - country
    - name
    type: object
  models.User:
    properties:
      cities:
        items:
          type: string
        type: array
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      refresh_token:
        type: string
      token:
        type: string
      updated_ad:
        type: string
      userId:
        type: string
    required:
    - email
    - password
    type: object
  models.WeatherData:
    properties:
      current:
        properties:
          cloud:
            type: integer
          condition:
            properties:
              code:
                type: integer
              icon:
                type: string
              text:
                type: string
            type: object
          feelslike_c:
            type: number
          feelslike_f:
            type: number
          gust_kph:
            type: number
          gust_mph:
            type: number
          humidity:
            type: integer
          is_day:
            type: integer
          last_updated:
            type: string
          last_updated_epoch:
            type: integer
          precip_in:
            type: number
          precip_mm:
            type: number
          pressure_in:
            type: number
          pressure_mb:
            type: number
          temp_c:
            type: number
          temp_f:
            type: number
          uv:
            type: number
          vis_km:
            type: number
          vis_miles:
            type: number
          wind_degree:
            type: integer
          wind_dir:
            type: string
          wind_kph:
            type: number
          wind_mph:
            type: number
        type: object
      location:
        properties:
          country:
            type: string
          lat:
            type: number
          localtime:
            type: string
          localtime_epoch:
            type: integer
          lon:
            type: number
          name:
            type: string
          region:
            type: string
          tz_id:
            type: string
        type: object
    type: object
info:
  contact: {}
paths:
  /cities:
    get:
      consumes:
      - application/json
      description: Autocomplete cities based on a search term
      parameters:
      - description: Search term for autocompletion
        in: query
        name: searchTerm
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.Error'
      summary: Autocomplete cities
      tags:
      - autocomplete cities city
  /currentWeather:
    delete:
      consumes:
      - application/json
      description: Add Current Weather using location and user information
      parameters:
      - description: Authorization Token
        in: header
        name: token
        required: true
        type: string
      - description: city name
        in: body
        name: city
        required: true
        schema:
          type: object
      - description: country name
        in: body
        name: country
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Successfully returned all the current weather by location entries
          schema:
            type: string
      summary: Remove Current Weather location from user
      tags:
      - add current weather location
    get:
      description: Retrieve current weather data for all cities associated with the
        user
      parameters:
      - description: Authorization Token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WeatherData'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.Error'
      summary: Get all current weather by city
    post:
      consumes:
      - application/json
      description: Add Current Weather location for user
      parameters:
      - description: Authorization Token
        in: header
        name: token
        required: true
        type: string
      - description: city name
        in: body
        name: city
        required: true
        schema:
          type: object
      - description: country name
        in: body
        name: country
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Successfully added current weather location
          schema:
            type: string
      summary: Add Current Weather location for user
      tags:
      - add current weather location
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a registered user and generates tokens
      parameters:
      - description: User's email address
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User's password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Login a user
  /register:
    get:
      consumes:
      - application/json
      description: Register a new user with email and password
      parameters:
      - description: User's email address
        format: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User's password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully registered, inserted document ID returned
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Register user
      tags:
      - register mobile app user
swagger: "2.0"
